% Files written: main.m, classic_qlearning.m, SSQL.m, plotting_results.m ; modifications in parameters.m, main1.m, populateCost.m, as well as a few others to correct initial errors in the authors’ code (probably an old version accidentally uploaded)
% Data is generated with the populate* functions, at the beginning of main1.m

clear all
close all

parameters;
main1;
save('run.txt','channelStates_dB','discount_factor',...
    'holdingCost',...
    'holdingCost0',...
    'holdingCost1',...
    'holdingCost2',...
    'holdingCost3','overflowCost','overflowCost0','overflowCost1',...
    'overflowCost2','overflowCost3',...
    'delay','delay0','delay1','delay2','delay3','power','power0','power1','power2','power3','-ascii');
save('run.mat','channelStates_dB','discount_factor',...
    'holdingCost',...
    'holdingCost0',...
    'holdingCost1',...
    'holdingCost2',...
    'holdingCost3','overflowCost','overflowCost0','overflowCost1',...
    'overflowCost2','overflowCost3',...
    'delay','delay0','delay1','delay2','delay3','power','power0','power1','power2','power3');

A=[holdingCost,...
    holdingCost0,...
    holdingCost1,...
    holdingCost2,...
    holdingCost3];
B=[power,power0,power1,power2,power3];
